# Generated by Django 4.2.3 on 2023-08-07 18:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Property',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('basin', models.CharField(max_length=50)),
                ('owner_of_record', models.CharField(max_length=50)),
                ('permit_num', models.CharField(max_length=20)),
                ('cert_status', models.CharField(max_length=20)),
                ('priority_date', models.DateField()),
                ('pod_1', models.CharField(max_length=10)),
                ('pod_2', models.CharField(max_length=10)),
                ('pod_3', models.CharField(max_length=10)),
                ('pod_4', models.CharField(max_length=10)),
                ('pod_5', models.CharField(max_length=10)),
                ('unit_acres', models.IntegerField()),
                ('unit_sheep', models.IntegerField()),
                ('unit_lamb', models.IntegerField()),
                ('unit_cattle', models.IntegerField()),
                ('unit_horses', models.IntegerField()),
                ('unit_other', models.CharField(max_length=30)),
                ('cfs', models.FloatField()),
                ('duty_af', models.FloatField()),
                ('poc_due', models.DateField()),
                ('pbu_due', models.DateField()),
                ('use', models.CharField(max_length=5)),
                ('source', models.CharField(max_length=5)),
                ('source_description', models.CharField(max_length=50)),
                ('remarks', models.CharField(max_length=50)),
                ('sale_value', models.CharField(max_length=100)),
                ('potential_values', models.CharField(max_length=150)),
                ('created_by', models.CharField(max_length=50)),
                ('modified_by', models.CharField(max_length=50)),
                ('create_date', models.DateTimeField(auto_now_add=True)),
                ('modify_date', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
