# Generated by Django 4.2.3 on 2023-08-07 22:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('permitinformation', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='property',
            name='basin',
            field=models.CharField(max_length=50, verbose_name='Basin'),
        ),
        migrations.AlterField(
            model_name='property',
            name='cert_status',
            field=models.CharField(blank=True, max_length=20, verbose_name='Cert./Status'),
        ),
        migrations.AlterField(
            model_name='property',
            name='cfs',
            field=models.FloatField(blank=True, verbose_name='C.F.S.'),
        ),
        migrations.AlterField(
            model_name='property',
            name='create_date',
            field=models.DateTimeField(auto_now_add=True, verbose_name=''),
        ),
        migrations.AlterField(
            model_name='property',
            name='created_by',
            field=models.CharField(blank=True, max_length=50, verbose_name=''),
        ),
        migrations.AlterField(
            model_name='property',
            name='duty_af',
            field=models.FloatField(blank=True, verbose_name='Duty (AF)'),
        ),
        migrations.AlterField(
            model_name='property',
            name='modified_by',
            field=models.CharField(blank=True, max_length=50, verbose_name=''),
        ),
        migrations.AlterField(
            model_name='property',
            name='modify_date',
            field=models.DateTimeField(auto_now=True, verbose_name=''),
        ),
        migrations.AlterField(
            model_name='property',
            name='owner_of_record',
            field=models.CharField(max_length=50, verbose_name='Owner of Record'),
        ),
        migrations.AlterField(
            model_name='property',
            name='pbu_due',
            field=models.DateField(blank=True, verbose_name='PBU Due'),
        ),
        migrations.AlterField(
            model_name='property',
            name='permit_num',
            field=models.CharField(max_length=20, verbose_name='Permit Number'),
        ),
        migrations.AlterField(
            model_name='property',
            name='poc_due',
            field=models.DateField(blank=True, verbose_name='POC Due'),
        ),
        migrations.AlterField(
            model_name='property',
            name='pod_1',
            field=models.CharField(blank=True, max_length=10, verbose_name='PoE 1/4'),
        ),
        migrations.AlterField(
            model_name='property',
            name='pod_2',
            field=models.CharField(blank=True, max_length=10, verbose_name='PoE 1/4'),
        ),
        migrations.AlterField(
            model_name='property',
            name='pod_3',
            field=models.CharField(blank=True, max_length=10, verbose_name='PoE S'),
        ),
        migrations.AlterField(
            model_name='property',
            name='pod_4',
            field=models.CharField(blank=True, max_length=10, verbose_name='PoE T(N)'),
        ),
        migrations.AlterField(
            model_name='property',
            name='pod_5',
            field=models.CharField(blank=True, max_length=10, verbose_name='PoE R'),
        ),
        migrations.AlterField(
            model_name='property',
            name='potential_values',
            field=models.CharField(blank=True, max_length=150, verbose_name='Potential Value'),
        ),
        migrations.AlterField(
            model_name='property',
            name='priority_date',
            field=models.DateField(blank=True, verbose_name='Priority Date'),
        ),
        migrations.AlterField(
            model_name='property',
            name='remarks',
            field=models.CharField(blank=True, max_length=50, verbose_name='Remarks'),
        ),
        migrations.AlterField(
            model_name='property',
            name='sale_value',
            field=models.CharField(blank=True, max_length=100, verbose_name='Sale Value'),
        ),
        migrations.AlterField(
            model_name='property',
            name='source',
            field=models.CharField(blank=True, max_length=5, verbose_name='Source'),
        ),
        migrations.AlterField(
            model_name='property',
            name='source_description',
            field=models.CharField(blank=True, max_length=50, verbose_name='Source Description'),
        ),
        migrations.AlterField(
            model_name='property',
            name='unit_acres',
            field=models.IntegerField(blank=True, verbose_name='Acres'),
        ),
        migrations.AlterField(
            model_name='property',
            name='unit_cattle',
            field=models.IntegerField(blank=True, verbose_name='Cattle'),
        ),
        migrations.AlterField(
            model_name='property',
            name='unit_horses',
            field=models.IntegerField(blank=True, verbose_name='Horses'),
        ),
        migrations.AlterField(
            model_name='property',
            name='unit_lamb',
            field=models.IntegerField(blank=True, verbose_name='Lamb'),
        ),
        migrations.AlterField(
            model_name='property',
            name='unit_other',
            field=models.CharField(blank=True, max_length=30, verbose_name='Other'),
        ),
        migrations.AlterField(
            model_name='property',
            name='unit_sheep',
            field=models.IntegerField(blank=True, verbose_name='Sheep'),
        ),
        migrations.AlterField(
            model_name='property',
            name='use',
            field=models.CharField(blank=True, max_length=5, verbose_name='Use'),
        ),
    ]
