# Generated by Django 4.2.3 on 2023-08-08 00:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('permitinformation', '0002_alter_property_basin_alter_property_cert_status_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='property',
            options={'verbose_name_plural': 'Properties'},
        ),
    ]
