# Generated by Django 4.2.3 on 2023-08-08 00:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('permitinformation', '0003_alter_property_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='property',
            name='pbu_due',
            field=models.DateField(blank=True, null=True, verbose_name='PBU Due'),
        ),
        migrations.AlterField(
            model_name='property',
            name='poc_due',
            field=models.DateField(blank=True, null=True, verbose_name='POC Due'),
        ),
        migrations.AlterField(
            model_name='property',
            name='priority_date',
            field=models.DateField(blank=True, null=True, verbose_name='Priority Date'),
        ),
    ]
