# Generated by Django 4.2.3 on 2023-08-08 00:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('permitinformation', '0004_alter_property_pbu_due_alter_property_poc_due_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='property',
            name='unit_acres',
            field=models.IntegerField(blank=True, null=True, verbose_name='Acres'),
        ),
        migrations.AlterField(
            model_name='property',
            name='unit_cattle',
            field=models.IntegerField(blank=True, null=True, verbose_name='Cattle'),
        ),
        migrations.AlterField(
            model_name='property',
            name='unit_horses',
            field=models.IntegerField(blank=True, null=True, verbose_name='Horses'),
        ),
        migrations.AlterField(
            model_name='property',
            name='unit_lamb',
            field=models.IntegerField(blank=True, null=True, verbose_name='Lamb'),
        ),
        migrations.AlterField(
            model_name='property',
            name='unit_sheep',
            field=models.IntegerField(blank=True, null=True, verbose_name='Sheep'),
        ),
    ]
