# Generated by Django 4.2.3 on 2023-08-23 22:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('permitinformation', '0008_property_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='property',
            name='unit_acres',
            field=models.FloatField(blank=True, null=True, verbose_name='Acres'),
        ),
    ]
